# Generated by Django 4.1 on 2023-03-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votante',
            name='codigo',
        ),
    ]
