# Generated by Django 4.1 on 2023-01-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='cedula',
            field=models.CharField(max_length=50, verbose_name='Cédula'),
        ),
    ]
