# Generated by Django 4.1 on 2023-03-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0002_remove_votante_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=150)),
                ('accion', models.CharField(choices=[(0, 'Obtener'), (1, 'Agregar'), (2, 'Actualizar'), (3, 'Eliminar')], default=0, max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[(0, 'Usuario'), (1, 'Dirigente'), (2, 'Votante'), (3, 'Residencia'), (4, 'Corregimiento'), (5, 'Operativo'), (6, 'Beneficio')], default=0, max_length=50)),
                ('estado', models.CharField(choices=[(0, 'error'), (1, 'success'), (2, 'warning'), (3, 'info')], default=0, max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['id'],
            },
        ),
    ]
