# Generated by Django 4.1 on 2023-01-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0002_alter_votante_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=50),
        ),
    ]
