# Generated by Django 4.1 on 2023-01-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0003_alter_votante_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='cedula',
            field=models.CharField(max_length=50, unique=True, verbose_name='Cédula'),
        ),
    ]
