# Generated by Django 4.1 on 2023-01-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0004_alter_votante_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, max_length=15, null=True, verbose_name='Código'),
        ),
    ]
