# Generated by Django 4.1 on 2023-01-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0005_alter_votante_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Código'),
        ),
    ]
