# Generated by Django 4.1 on 2023-04-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0007_alter_eventolog_accion_alter_eventolog_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventolog',
            name='accion',
            field=models.CharField(choices=[('0', 'Obtener'), ('1', 'Agregar'), ('2', 'Actualizar'), ('3', 'Eliminar')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='eventolog',
            name='estado',
            field=models.CharField(choices=[('0', 'error'), ('1', 'success'), ('2', 'warning'), ('3', 'info')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='eventolog',
            name='tipo',
            field=models.CharField(choices=[('0', 'Usuario'), ('1', 'Dirigente'), ('2', 'Votante'), ('3', 'Residencia'), ('4', 'Corregimiento'), ('5', 'Operativo'), ('6', 'Beneficio')], default=0, max_length=50),
        ),
    ]
